# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8542e3d2cc44fa1281997ae30e34c804815577263fe8c97c099c2ce5f070e1fbaabc30f6d7d0534f1123a31eba22407017e860be0bf8364caa914d74012d11a

test:
  secret_key_base: 7103964e70e2a6387603d449997ddc0ef0bec265ea28f5956d2e52044584b57d1bdbba329fb5f9b6cfea7e22106b60870904da2e27dfe56cfe3921f590c15f65

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
